### PR TITLE
Various fixes

### LINKED ISSUE #21: Fix tests

### PR DESCRIPTION
**Pull request by FloopCZ**
- closes #21

### CODE REVIEW

**Comment by gdynusa** [comment]
@FloopCZ accidentally created branch of same name, hope it doesn't matter

**Comment by gdynusa** [comment]
closes #22

**Comment by FloopCZ** [comment]
I push forced the branch without your commits. Please create a new pull request and a new branch for this @gdynusa.

**Comment by FloopCZ** [comment]
@petrbel note that the tests won't pass until #24 is fixed.

**Review by petrbel — APPROVED** [review]
I approve, but since I've made some changes, @FloopCZ should see them before merging (feel free to merge anytime)
- emloop release (github)
- emloop release upload to emloop-examples
- fix emloop version to be tested (0.12.0 -> 0.1.0)
- removed old releases (github)
- update pritunl docker image to archimg/base-devel
- use `pacman -Syu`
- pass tests
- set up coveralls

@gdynusa please make sure you don't push (force) to this branch until it's merged (it's very very fragile)

**Comment by FloopCZ** [comment]
Thank you for your changes @petrbel, they look good. I made one additional commit, feel free to merge when (if) the tests pass.

**Pull request merged**
